### ISSUE TITLE
How to pass message list to chat controller?

### ISSUE THREAD

**Issue by abdulhaseeb06** [tkhiking/chat-ui-react#6]
I want to pass message list to chat controller and render it. But I'm not able to do so.
` chatCtl.state.messages = response.data.Response.messages.map(
                    (item) => ({
                      type: 'text',
                      content: item.Description,
                      self: item.Sender,
                      createdAt: new Date(),
                    })
                  );`

The list is rendered only after a new message is typed and sent.

**Comment by tkhiking** [comment]
Hi @abdulhaseeb06,
Please use `ChatController.setMessages()` to pass messages to the chat controller.
`ChatController.setMessages()` is now available in v0.2.10 just released.

**Comment by abdulhaseeb06** [comment]
Thanks a lot +1:

**Comment by tkhiking** [comment]
I'm glad to help you.
